name: mercuryhealth-web-ci  
on: [push]

jobs: 
 build:  
  runs-on: ubuntu-latest  
  steps:  
  - uses: actions/checkout@v1  
  - name: Setup .NET Core SDK  
    uses: actions/setup-dotnet@v1
    with:
        dotnet-version: 5.0.x
  - name: Restore dependencies
    run: dotnet restore
  - name: Build
    run: dotnet build -c Release
  - name: Test
    run: dotnet test -c Release
