name: mercuryhealth-web-ci  
on: [push]

env:
  AZURE_WEBAPP_NAME: hdsampledotnetcore    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root

jobs: 
 build-deploy-app:  
  runs-on: ubuntu-latest  
  steps:  
  - uses: actions/checkout@v1  
  - name: Setup .NET Core SDK  
    uses: actions/setup-dotnet@v1
    with:
        dotnet-version: 5.0.x
  - name: Restore dependencies
    run: dotnet restore
  - name: Build
    run: dotnet build -c Release
  - name: Test
    run: dotnet test -c Release
  
  - name: 'Run Azure webapp deploy action using publish profile credentials'
    uses: azure/webapps-deploy@v2
    with: 
      app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
      publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
      package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/hdsampledotnetcore'
